// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using carGooBackend.Data;

#nullable disable

namespace carGooBackend.Migrations
{
    [DbContext(typeof(CarGooDataContext))]
    partial class CarGooDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8a000e3b-b915-43f1-b90e-b28075ec8cac",
                            ConcurrencyStamp = "8a000e3b-b915-43f1-b90e-b28075ec8cac",
                            Name = "Dispecer",
                            NormalizedName = "DISPECER"
                        },
                        new
                        {
                            Id = "415a7c65-81dd-4fe3-9c44-9493db860c4b",
                            ConcurrencyStamp = "415a7c65-81dd-4fe3-9c44-9493db860c4b",
                            Name = "Prevoznik",
                            NormalizedName = "PREVOZNIK"
                        },
                        new
                        {
                            Id = "415a7c65-81dd-4fe3-9c44-9493db860c4c",
                            ConcurrencyStamp = "415a7c65-81dd-4fe3-9c44-9493db860c4c",
                            Name = "Kontroler",
                            NormalizedName = "KONTROLER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("carGooBackend.Models.Korisnik", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PreduzeceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserPicture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PreduzeceId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("carGooBackend.Models.Obavestenje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumObjavljivanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Obavestenje");
                });

            modelBuilder.Entity("carGooBackend.Models.Ponuda", b =>
                {
                    b.Property<Guid>("PonudaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cena")
                        .HasColumnType("integer");

                    b.Property<string>("DrzavaI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrzavaU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Duzina")
                        .HasColumnType("double precision");

                    b.Property<string>("IdKorisnika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdPreduzeca")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Istovar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MestoI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MestoU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tezina")
                        .HasColumnType("double precision");

                    b.Property<string>("TipKamiona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipNadogradnje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Utovar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Vreme")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VrstaTereta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZamenaPaleta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PonudaId");

                    b.HasIndex("IdKorisnika");

                    b.HasIndex("IdPreduzeca");

                    b.ToTable("Ponude");
                });

            modelBuilder.Entity("carGooBackend.Models.PonudaVozila", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DrzavaI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrzavaU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Duzina")
                        .HasColumnType("double precision");

                    b.Property<string>("IdKorisnika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdPreduzeca")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Istovar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MestoI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MestoU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RadiusI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tezina")
                        .HasColumnType("double precision");

                    b.Property<string>("TipKamiona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipNadogradnje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Utovar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Vreme")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdKorisnika");

                    b.HasIndex("IdPreduzeca");

                    b.ToTable("PonudaVozila");
                });

            modelBuilder.Entity("carGooBackend.Models.Preduzece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyPIB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Preduzeca");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("carGooBackend.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("carGooBackend.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("carGooBackend.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("carGooBackend.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("carGooBackend.Models.Korisnik", b =>
                {
                    b.HasOne("carGooBackend.Models.Preduzece", "Preduzece")
                        .WithMany("Korisnici")
                        .HasForeignKey("PreduzeceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preduzece");
                });

            modelBuilder.Entity("carGooBackend.Models.Obavestenje", b =>
                {
                    b.HasOne("carGooBackend.Models.Korisnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("carGooBackend.Models.Ponuda", b =>
                {
                    b.HasOne("carGooBackend.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("carGooBackend.Models.Preduzece", "Preduzece")
                        .WithMany()
                        .HasForeignKey("IdPreduzeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Preduzece");
                });

            modelBuilder.Entity("carGooBackend.Models.PonudaVozila", b =>
                {
                    b.HasOne("carGooBackend.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("carGooBackend.Models.Preduzece", "Preduzece")
                        .WithMany()
                        .HasForeignKey("IdPreduzeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Preduzece");
                });

            modelBuilder.Entity("carGooBackend.Models.Preduzece", b =>
                {
                    b.Navigation("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
